#!/bin/bash

# This script will clean the rootfs for a normal usage.
# Globally, it will cancel effects of the builder-enter script.
# It also clean rootfs to make image "forkable"

set -e

# remove ssh host keys so they are regenerated on first boot
rm -f /etc/ssh/*_key*

# clean history
rm -f /root/.history /root/.bash_history

# Update locate cache
updatedb 2>/dev/null || true
